graph [
			 edge [ source 1 target 2 label "-" ]
			node [ id 1 label "C" ]
			node [ id 2 label "O" ]
			 edge [ source 1 target 3 label "-" ]
			node [ id 3 label "H" ]
			 edge [ source 1 target 4 label "-" ]
			node [ id 4 label "H" ]
			 edge [ source 1 target 5 label "-" ]
			node [ id 5 label "H" ]
			 edge [ source 2 target 6 label "-" ]
			node [ id 6 label "O" ]
			 edge [ source 7 target 8 label "=" ]
			node [ id 7 label "O" ]
			node [ id 8 label "C" ]
			 edge [ source 8 target 9 label "-" ]
			node [ id 9 label "C" ]
			 edge [ source 8 target 10 label "-" ]
			node [ id 10 label "O" ]
			 edge [ source 9 target 11 label "-" ]
			node [ id 11 label "C" ]
			 edge [ source 6 target 11 label "-" ]
			 edge [ source 9 target 12 label "=" ]
			node [ id 12 label "O" ]
			 edge [ source 11 target 13 label "-" ]
			node [ id 13 label "C" ]
			 edge [ source 10 target 13 label "-" ]
			 edge [ source 11 target 14 label "-" ]
			node [ id 14 label "O" ]
			 edge [ source 13 target 15 label "-" ]
			node [ id 15 label "C" ]
			 edge [ source 13 target 16 label "-" ]
			node [ id 16 label "H" ]
			 edge [ source 15 target 17 label "-" ]
			node [ id 17 label "C" ]
			 edge [ source 15 target 18 label "-" ]
			node [ id 18 label "O" ]
			 edge [ source 15 target 19 label "-" ]
			node [ id 19 label "H" ]
			 edge [ source 17 target 20 label "-" ]
			node [ id 20 label "O" ]
			 edge [ source 17 target 21 label "-" ]
			node [ id 21 label "H" ]
			 edge [ source 17 target 22 label "-" ]
			node [ id 22 label "H" ]
			 edge [ source 20 target 23 label "-" ]
			node [ id 23 label "H" ]
			 edge [ source 18 target 24 label "-" ]
			node [ id 24 label "H" ]
			 edge [ source 14 target 25 label "-" ]
			node [ id 25 label "H" ]
]