graph [
			 edge [ source 1 target 2 label "=" ]
			node [ id 1 label "O" ]
			node [ id 2 label "C" ]
			 edge [ source 2 target 3 label "-" ]
			node [ id 3 label "C" ]
			 edge [ source 2 target 4 label "-" ]
			node [ id 4 label "O" ]
			 edge [ source 3 target 5 label "=" ]
			node [ id 5 label "C" ]
			 edge [ source 3 target 6 label "-" ]
			node [ id 6 label "O" ]
			 edge [ source 5 target 7 label "-" ]
			node [ id 7 label "C." ]
			 edge [ source 4 target 7 label "-" ]
			 edge [ source 5 target 8 label "-" ]
			node [ id 8 label "O" ]
			 edge [ source 7 target 9 label "-" ]
			node [ id 9 label "C" ]
			 edge [ source 9 target 10 label "-" ]
			node [ id 10 label "C" ]
			 edge [ source 9 target 11 label "-" ]
			node [ id 11 label "O" ]
			 edge [ source 9 target 12 label "-" ]
			node [ id 12 label "H" ]
			 edge [ source 10 target 13 label "-" ]
			node [ id 13 label "O" ]
			 edge [ source 10 target 14 label "-" ]
			node [ id 14 label "H" ]
			 edge [ source 10 target 15 label "-" ]
			node [ id 15 label "H" ]
			 edge [ source 6 target 16 label "-" ]
			node [ id 16 label "H" ]
			 edge [ source 13 target 17 label "-" ]
			node [ id 17 label "H" ]
			 edge [ source 11 target 18 label "-" ]
			node [ id 18 label "H" ]
			 edge [ source 8 target 19 label "-" ]
			node [ id 19 label "H" ]
]