graph [
			 edge [ source 1 target 2 label "-" ]
			node [ id 1 label "C" ]
			node [ id 2 label "O" ]
			 edge [ source 1 target 3 label "-" ]
			node [ id 3 label "H" ]
			 edge [ source 1 target 4 label "-" ]
			node [ id 4 label "H" ]
			 edge [ source 1 target 5 label "-" ]
			node [ id 5 label "H" ]
			 edge [ source 2 target 6 label "-" ]
			node [ id 6 label "O" ]
			 edge [ source 6 target 7 label "-" ]
			node [ id 7 label "H" ]
]