rule [
	ruleID " ch3oo_vitc_PATH_10_13"
	left [
			 edge [ source 13 target 25 label "-" ]
			node [ id 6 label "O." ]
			node [ id 13 label "C" ]

	]
	context [
			node [ id 1 label "C" ]
			node [ id 2 label "O" ]
			node [ id 3 label "H" ]
			node [ id 4 label "H" ]
			node [ id 5 label "H" ]
			node [ id 7 label "O" ]
			node [ id 8 label "C" ]
			node [ id 9 label "C" ]
			node [ id 10 label "C" ]
			node [ id 11 label "C" ]
			node [ id 12 label "C" ]
			node [ id 14 label "O" ]
			node [ id 15 label "O" ]
			node [ id 16 label "O" ]
			node [ id 17 label "O" ]
			node [ id 18 label "H" ]
			node [ id 19 label "O" ]
			node [ id 20 label "H" ]
			node [ id 21 label "H" ]
			node [ id 22 label "H" ]
			node [ id 23 label "H" ]
			node [ id 24 label "H" ]
			node [ id 25 label "H" ]
			node [ id 26 label "H" ]
			 edge [ source 1 target 2 label "-" ]
			 edge [ source 1 target 3 label "-" ]
			 edge [ source 1 target 4 label "-" ]
			 edge [ source 1 target 5 label "-" ]
			 edge [ source 10 target 11 label "-" ]
			 edge [ source 10 target 19 label "-" ]
			 edge [ source 11 target 12 label "-" ]
			 edge [ source 11 target 14 label "-" ]
			 edge [ source 11 target 23 label "-" ]
			 edge [ source 12 target 13 label "-" ]
			 edge [ source 12 target 17 label "-" ]
			 edge [ source 12 target 24 label "-" ]
			 edge [ source 13 target 16 label "-" ]
			 edge [ source 13 target 26 label "-" ]
			 edge [ source 15 target 18 label "-" ]
			 edge [ source 16 target 22 label "-" ]
			 edge [ source 17 target 21 label "-" ]
			 edge [ source 19 target 20 label "-" ]
			 edge [ source 2 target 6 label "-" ]
			 edge [ source 7 target 8 label "=" ]
			 edge [ source 8 target 14 label "-" ]
			 edge [ source 8 target 9 label "-" ]
			 edge [ source 9 target 10 label "=" ]
			 edge [ source 9 target 15 label "-" ]

	]
	right [
			 edge [ source 6 target 25 label "-" ]
			node [ id 13 label "C." ]
			node [ id 6 label "O" ]

	]
]